-- 代码走查非法数据页需要保留老平台字段语义，事实层集中承载这些稳定值。
alter table code_review_external_metrics add column if not exists scan_status varchar(128);
alter table code_review_external_metrics add column if not exists scan_bug_count integer;
alter table code_review_external_metrics add column if not exists annotation_rate_result varchar(128);
alter table code_review_external_metrics add column if not exists bug_count_result varchar(128);
alter table code_review_external_metrics add column if not exists deleted_lines integer;
alter table code_review_external_metrics add column if not exists code_specification_count integer;
alter table code_review_external_metrics add column if not exists code_logic_specification_count integer;
alter table code_review_external_metrics add column if not exists performance_specification_count integer;
alter table code_review_external_metrics add column if not exists design_specification_count integer;
alter table code_review_external_metrics add column if not exists other_specification_count integer;
alter table code_review_external_metrics add column if not exists review_speed_loc_per_hour integer;
alter table code_review_external_metrics add column if not exists review_speed_kloc_per_hour numeric(10, 2);
alter table code_review_external_metrics add column if not exists review_defect_density_per_kloc numeric(10, 2);
alter table code_review_external_metrics add column if not exists review_efficiency_per_hour numeric(10, 2);
alter table code_review_external_metrics add column if not exists commit_count integer;
alter table code_review_external_metrics add column if not exists commit_rate integer;
alter table code_review_external_metrics add column if not exists function_name varchar(255);
alter table code_review_external_metrics add column if not exists clang_added_line_count integer;

alter table merge_request_fact add column if not exists annotation_rate_result varchar(128);
alter table merge_request_fact add column if not exists bug_count_result varchar(128);
alter table merge_request_fact add column if not exists deleted_lines integer;
alter table merge_request_fact add column if not exists code_specification_count integer;
alter table merge_request_fact add column if not exists code_logic_specification_count integer;
alter table merge_request_fact add column if not exists performance_specification_count integer;
alter table merge_request_fact add column if not exists design_specification_count integer;
alter table merge_request_fact add column if not exists other_specification_count integer;
alter table merge_request_fact add column if not exists review_speed_loc_per_hour integer;
alter table merge_request_fact add column if not exists review_speed_kloc_per_hour numeric(10, 2);
alter table merge_request_fact add column if not exists review_defect_density_per_kloc numeric(10, 2);
alter table merge_request_fact add column if not exists review_efficiency_per_hour numeric(10, 2);
alter table merge_request_fact add column if not exists commit_count integer;
alter table merge_request_fact add column if not exists commit_rate integer;
alter table merge_request_fact add column if not exists function_name varchar(255);
alter table merge_request_fact add column if not exists clang_added_line_count integer;
