import {
  AlarmClock,
  Bell,
  Calendar,
  CollectionTag,
  Connection,
  DataAnalysis,
  DataBoard,
  DataLine,
  Document,
  DocumentChecked,
  Memo,
  Monitor,
  Operation,
  PieChart,
  Search,
  Setting,
  Tickets,
  Timer,
  Tools,
} from '@element-plus/icons-vue';

import type { ShellModule } from './types';

export const modules: ShellModule[] = [
  {
    key: 'quality-board',
    label: '质量看板',
    icon: DataAnalysis,
    title: '质量看板',
    description: '对齐老平台质量看板模块，统一承载研发质量看板及其他看板入口。',
    pages: [
      {
        key: 'quality-board-rd-quality-board',
        label: '研发质量看板',
        icon: DataBoard,
        description: '聚合评审、代码走查与系统测试关键信号的研发质量概览。',
        path: '/quality-board/rd-quality-board',
        permission: 'quality.rd.view',
      },
      {
        key: 'quality-board-other-board',
        label: '其他看板',
        icon: PieChart,
        description: '对齐老平台其他看板，展示质量指标和人员维度质量图表。',
        path: '/quality-board/other-board',
        permission: 'quality.other.view',
      },
    ],
  },
  {
    key: 'review-data',
    label: '评审数据',
    icon: Document,
    title: '评审数据',
    description: '承载评审记录查看、维护以及问题清单管理的记录类页面。',
    pages: [
      {
        key: 'review-data-home',
        label: '评审数据管理',
        icon: DocumentChecked,
        description: '展示评审主记录、评审专家以及问题清单明细。',
        path: '/review-data/home',
        requiresLogin: true,
        hiddenForApproval: true,
        permission: 'review.data.view',
      },
    ],
  },
  {
    key: 'code-review',
    label: '代码走查',
    icon: Operation,
    title: '代码走查',
    description: '承载代码走查相关的记录页与统计看板入口。',
    pages: [
      {
        key: 'code-review-illegal-records',
        label: '代码走查非法数据',
        icon: CollectionTag,
        description: '展示代码走查场景下的非法记录明细列表。',
        path: '/code-review/illegal-records',
        hiddenForApproval: true,
        permission: 'code_review.illegal.view',
      },
      {
        key: 'code-review-multi-board',
        label: '代码走查多元看板',
        icon: DataLine,
        description: '围绕数据源切换、模块分布与责任人分布的代码走查图表看板。',
        path: '/code-review/multi-board',
        requiresLogin: true,
        hiddenForApproval: true,
        permission: 'code_review.board.view',
      },
    ],
  },
  {
    key: 'question-metrics',
    label: '系统测试',
    icon: DataAnalysis,
    title: '系统测试',
    description: '统一承载系统测试议题的汇总、分析、非法数据和查询入口。',
    pages: [
      {
        key: 'question-metrics-home',
        label: '系统测试缺陷汇总',
        icon: DataAnalysis,
        description: '展示系统测试缺陷的多级统计表头与模块维度汇总。',
        path: '/question-metrics/home',
        hiddenForApproval: true,
        permission: 'system_test.summary.view',
      },
      {
        key: 'question-metrics-multi-board',
        label: '议题多元看板',
        icon: DataBoard,
        description: '聚合系统测试核心统计板结果的图表化看板入口。',
        path: '/question-metrics/multi-board',
        requiresLogin: true,
        hiddenForApproval: true,
        permission: 'system_test.board.view',
      },
      {
        key: 'question-metrics-delay-analysis',
        label: '申请延期缺陷分析',
        icon: Timer,
        description: '展示系统测试延期原因维度下的一二三级、建议类与总计缺陷统计，并支持下钻明细。',
        path: '/question-metrics/delay-analysis',
        requiresLogin: true,
        hiddenForApproval: true,
        permission: 'system_test.delay.view',
      },
      {
        key: 'question-metrics-illegal-records',
        label: '系统测试非法数据',
        icon: CollectionTag,
        description: '展示系统测试范围内命中非法规则的议题明细，并支持规则说明和筛选。',
        path: '/question-metrics/illegal-records',
        permission: 'system_test.illegal.view',
      },
      {
        key: 'question-metrics-defect-cause',
        label: '缺陷原因分析',
        icon: PieChart,
        description: '展示系统测试缺陷在模块维度下的原因归类统计，并支持按原因下钻明细。',
        path: '/question-metrics/defect-cause',
        permission: 'system_test.cause.view',
      },
      {
        key: 'question-metrics-phase-statistics',
        label: '议题阶段统计',
        icon: DataLine,
        description: '展示系统测试轮次维度的一级、二级、三级、建议类及总量统计。',
        path: '/question-metrics/phase-statistics',
        permission: 'system_test.phase.view',
      },
      {
        key: 'question-metrics-issue-search',
        label: '议题查询',
        icon: Search,
        description: '对齐老平台议题查询入口，当前先补齐查询类副模块骨架。',
        path: '/question-metrics/issue-search',
        permission: 'system_test.issue.view',
      },
    ],
  },
  {
    key: 'customer-issues',
    label: '客户问题',
    icon: Bell,
    title: '客户问题',
    description: '统一承载客户问题统计、缺陷分析以及专题查询入口。',
    pages: [
      {
        key: 'customer-issues-home',
        label: '缺陷汇总',
        icon: DataAnalysis,
        description: '展示客户问题范围下的多级统计表头与模块维度缺陷汇总。',
        path: '/customer-issues/home',
        hiddenForApproval: true,
        permission: 'customer_issue.summary.view',
      },
      {
        key: 'customer-issues-illegal-records',
        label: '缺陷非法数据',
        icon: CollectionTag,
        description: '对齐老平台客户问题统计下的缺陷非法数据入口。',
        path: '/customer-issues/illegal-records',
        permission: 'customer_issue.illegal.view',
      },
      {
        key: 'customer-issues-defect-cause',
        label: '缺陷原因分析',
        icon: PieChart,
        description: '展示客户问题在模块维度下的缺陷原因归类统计，并支持按原因下钻明细。',
        path: '/customer-issues/defect-cause',
        permission: 'customer_issue.cause.view',
      },
      {
        key: 'customer-issues-cc-product-issues',
        label: 'CC_PRODUCT议题',
        icon: Tickets,
        description: '对齐老平台客户问题统计下的 CC_PRODUCT 议题入口。',
        path: '/customer-issues/cc-product-issues',
        hiddenForApproval: true,
        permission: 'customer_issue.record.view',
      },
      {
        key: 'customer-issues-delay-issues',
        label: '延期问题',
        icon: AlarmClock,
        description: '对齐老平台客户问题统计下的延期问题入口。',
        path: '/customer-issues/delay-issues',
        permission: 'customer_issue.delay.view',
      },
      {
        key: 'customer-issues-response-efficiency',
        label: '缺陷响应效率',
        icon: Timer,
        description: '对齐老平台客户问题统计下的缺陷响应效率入口。',
        path: '/customer-issues/response-efficiency',
        permission: 'customer_issue.efficiency.view',
      },
      {
        key: 'customer-issues-issue-by-function',
        label: '按功能展示缺陷数量',
        icon: Memo,
        description: '对齐老平台客户问题统计下的按功能展示缺陷数量入口。',
        path: '/customer-issues/issue-by-function',
        permission: 'customer_issue.function.view',
      },
    ],
  },
  {
    key: 'system-settings',
    label: '系统设置',
    icon: Setting,
    title: '系统设置',
    description: '维护 GitLab 数据镜像、数据库查看与系统配置。',
    pages: [
      {
        key: 'label-group-settings',
        label: '标签组管理',
        icon: CollectionTag,
        description: '维护同维度标签值集合，供业务页面作为整体筛选条件使用。',
        path: '/system-settings/label-group-settings',
        requiresLogin: true,
        hiddenForApproval: true,
        permission: 'system.label_group.view',
      },
      {
        key: 'testing-phase-definition',
        label: '议题测试阶段定义',
        icon: Calendar,
        description: '维护系统测试和客户问题统计使用的阶段名称与测试轮次。',
        path: '/system-settings/testing-phase-definition',
        requiresLogin: true,
        hiddenForApproval: true,
        permission: 'system.testing_phase.view',
      },
      {
        key: 'mirror-settings',
        label: '数据镜像设置',
        icon: Connection,
        description: '管理 GitLab 数据镜像的连接、同步和日志。',
        path: '/system-settings/mirror-settings',
        requiresLogin: true,
        hiddenForApproval: true,
        permission: 'system.mirror.view',
      },
      // 兼容模式-MatchMode：临时页面入口，老平台数据库交接完成后可整体删除该 pageKey/path 及对应路由、API、后端 Controller。
      {
        key: 'database-settings',
        label: '数据库兼容模式临时设置',
        icon: Tools,
        description: '临时配置老平台兼容模式数据库连接、同步开关和转正式导入。',
        path: '/system-settings/database-settings',
        requiresLogin: true,
        hiddenForApproval: true,
        permission: 'system.match_mode.view',
      },
      {
        key: 'database-browser',
        label: '数据库查看',
        icon: Monitor,
        description: '快速浏览本地平台数据库中的核心业务表数据。',
        path: '/system-settings/database-browser',
        requiresLogin: true,
        hiddenForApproval: true,
        permission: 'system.database.view',
      },
      {
        key: 'permission-settings',
        label: '权限设置',
        icon: Tools,
        description: '维护数据采集平台本地角色权限。',
        path: '/system-settings/permission-settings',
        requiresLogin: true,
        hiddenForApproval: true,
        permission: 'system.permission.view',
      },
    ],
  },
];
